name: basic-chatbot-env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.12
  - numpy=2.3
  - pytorch=2.6.0
  - datasets=4.4.1
  - transformers=4.57.1
  - accelerate==1.11.0
  - matplotlib=3.10
  - jupyter=1.1
  - pip
